const dogs = [
    {"name":"Annie the Afgan Hound","id":0,"exercise":4,"intelligence":1,"friendliness":18,"drool":2},
    {"name":"Bertie the Boxer","id":1,"exercise":2,"intelligence":19,"friendliness":57,"drool":4},
    {"name":"Betty the Borzoi","id":2,"exercise":1,"intelligence":60,"friendliness":18,"drool":2},
    {"name":"Charlie the Chihuahua","id":3,"exercise":2,"intelligence":89,"friendliness":41,"drool":5},
    {"name":"Chaz the Cocker Spaniel","id":4,"exercise":4,"intelligence":37,"friendliness":60,"drool":2},
    {"name":"Donald the Dalmatian","id":5,"exercise":4,"intelligence":90,"friendliness":64,"drool":9},
    {"name":"Dottie the Doberman","id":6,"exercise":2,"intelligence":49,"friendliness":67,"drool":0},
    {"name":"Fern the Fox Terrier","id":7,"exercise":2,"intelligence":61,"friendliness":70,"drool":3},
    {"name":"Frank the French Bulldog","id":8,"exercise":0,"intelligence":59,"friendliness":62,"drool":1},
    {"name":"George the Great Dane","id":9,"exercise":4,"intelligence":38,"friendliness":93,"drool":6},
    {"name":"Gertie the Greyhound","id":10,"exercise":3,"intelligence":45,"friendliness":7,"drool":9},
    {"name":"Harry the Harrier","id":11,"exercise":0,"intelligence":37,"friendliness":64,"drool":8},
    {"name":"Ian the Irish Wolfhound","id":12,"exercise":2,"intelligence":24,"friendliness":31,"drool":6},
    {"name":"Juno the Jack Russell","id":13,"exercise":2,"intelligence":71,"friendliness":73,"drool":0},
    {"name":"Keith the Kerry Blue","id":14,"exercise":4,"intelligence":44,"friendliness":42,"drool":7},
    {"name":"Larry the Labrador","id":15,"exercise":2,"intelligence":16,"friendliness":39,"drool":8},
    {"name":"Marge the Maltese","id":16,"exercise":4,"intelligence":45,"friendliness":76,"drool":9},
    {"name":"Max the Mutt","id":17,"exercise":1,"intelligence":97,"friendliness":37,"drool":7},
    {"name":"Nutty the Newfoundland","id":18,"exercise":2,"intelligence":96,"friendliness":3,"drool":0},
    {"name":"Olive the Old English Sheepdog","id":19,"exercise":2,"intelligence":1,"friendliness":94,"drool":6},
    {"name":"Peter the Pug","id":20,"exercise":3,"intelligence":61,"friendliness":0,"drool":2},
    {"name":"Poppy the Pekingese","id":21,"exercise":3,"intelligence":72,"friendliness":47,"drool":9},
    {"name":"Rosie the Rottweiler","id":22,"exercise":2,"intelligence":51,"friendliness":7,"drool":2},
    {"name":"Ruby the Retriever","id":23,"exercise":0,"intelligence":80,"friendliness":20,"drool":5},
    {"name":"Sam the Springer Spaniel","id":24,"exercise":4,"intelligence":38,"friendliness":3,"drool":1},
    {"name":"Sukie the Saluki","id":25,"exercise":2,"intelligence":50,"friendliness":26,"drool":4},
    {"name":"Vernon the Vizsla","id":26,"exercise":3,"intelligence":1,"friendliness":89,"drool":1},
    {"name":"Whilma the West Highland Terrier","id":27,"exercise":2,"intelligence":17,"friendliness":39,"drool":8},
    {"name":"William the Whippet","id":28,"exercise":4,"intelligence":42,"friendliness":72,"drool":0},
    {"name":"Yolande the Yorkshire Terrier","id":29,"exercise":3,"intelligence":36,"friendliness":72,"drool":8}
  ];